<a href="https://colab.research.google.com/github/rolozanod/mexico_fuel_guided_project/blob/main/Sessions/ColabSession2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%load_ext autoreload
%autoreload 2

# Session 4 Optimizing scenarios

1. Create scenarios according to the objectives of the projects to evaluate
1. Estimate freight rates
1. Create the production random variables
1. Create the optmization model
1. Test the optimization model
1. Initiate the optimization loop

In [2]:
#!git clone https://github.com/rolozanod/mexico_fuel_guided_project.git

In [3]:
#!pip install geopandas

In [4]:
#!unzip /content/mexico_fuel_guided_project/data.zip -d /content/mexico_fuel_guided_project

# Get optimization algorithms

In [5]:
#!apt-get install -y -qq glpk-utils

In [6]:
import os
import numpy as np
import pandas as pd
os.chdir('/content/mexico_fuel_guided_project')
os.getcwd()

'/content/mexico_fuel_guided_project'

In [7]:
!ls

 README.md					    data.zip
 Sessions					    demand.csv
'\content\scenarios\'				    geoinfo.csv
'\content\scenarios\baseline\LOGS\baseline_0.log'   modules
 capacity.csv					    short_censo2020.csv
 cpts

In [8]:
from modules.sessions import Session4 as sess

# Create scenarios

We can create different scenarios as seen in last video.

But an optimization model that maximized on daily observations would be huge.

The model will be built to optmize monthly observations.

# Create a monthly time series

In [9]:
opt_periods = 8

INIT_DATE = '2021-01-01'
FINAL_DATE = '2021-12-31'

BATCH_SIZE = 16 # number of windows per batch
FORECAST_WINDOW = 1 # days to forecast
HINGESIGHT_WINDOW = 7*8+1 # days used for prediction

w = sess().WindowGenerator(input_width=HINGESIGHT_WINDOW, label_width=FORECAST_WINDOW, batch=BATCH_SIZE, min_share=0.1, keep_above=0.9)

price, demand, period_stats = sess().monthly_data(version=0, window=w, init_date=INIT_DATE, final_date=FINAL_DATE, plot=True)

Score: 0.8760367581634618

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

Timesteps: 1520
Locations: 88

Date: 2021-12-31 00:00:00: 100%|██████████| 365/365 [00:13<00:00, 27.73it/s]

In [10]:
period_stats

         days   T
date
2021-01    31   0
2021-02    28   1
2021-03    31   2
2021-04    30   3
2021-05    31   4
2021-06    30   5
2021-07    31   6
2021-08    31   7
2021-09    30   8
2021-10    31   9
2021-11    30  10
2021-12    31  11

In [11]:
demand

,date,state,loc,T,litres
0,2021-01,Aguascalientes,Aguascalientes,0,1.297327e+09
1,2021-01,Aguascalientes,Aguascalientes_aggregate(10),0,4.299085e+08
2,2021-01,Baja California,Baja California_aggregate(5),0,2.979073e+09
3,2021-01,Baja California,Tijuana,0,3.326895e+09
4,2021-01,Baja California Sur,Baja California Sur_aggregate(5),0,1.297112e+09
...,...,...,...,...,...
1051,2021-12,Yucatán,Yucatán_aggregate(86),11,2.418099e+09
1052,2021-12,Zacatecas,Fresnillo,11,2.115252e+08
1053,2021-12,Zacatecas,Guadalupe,11,2.999138e+08
1054,2021-12,Zacatecas,Zacatecas,11,1.959781e+08
1055,2021-12,Zacatecas,Zacatecas_aggregate(40),11,6.812685e+08

# Estimate freight

The coordinates of each location are stored in the WindowGenerator object and the coordinates for the refineries are in the unzipped data, so we estimate the distance between them using the __[haversine function](https://en.wikipedia.org/wiki/Haversine_formula)__

In [12]:
distances = sess().get_distances(window=w)

In [13]:
demand.state.unique()

array(['Aguascalientes', 'Baja California', 'Baja California Sur',
       'Campeche', 'Chiapas', 'Chihuahua', 'Ciudad de México',
       'Coahuila de Zaragoza', 'Colima', 'Durango', 'Guanajuato',
       'Guerrero', 'Hidalgo', 'Jalisco', 'Michoacán de Ocampo', 'Morelos',
       'México', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro',
       'Quintana Roo', 'San Luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco',
       'Tamaulipas', 'Tlaxcala', 'Veracruz de Ignacio de la Llave',
       'Yucatán', 'Zacatecas'], dtype=object)

We will esteimate freight in a very simple way, having the distances we will define a cost per kilometer and we can modify specifically some locations if we want to do so be cause we have some extra information on the regions geography or highways.

In [14]:
overall_mxnxkms = 5
pipe_size = 20000
diesel_weight = (0.8508+0.7489)/2 # 0.8508 is for fuel, 0.7489 is for gasoline
pipe_weight = diesel_weight*pipe_size
overall_mxnxkms_L = overall_mxnxkms/pipe_weight

freight = distances.copy()
freight['freightxkms'] = overall_mxnxkms_L
        
freight['freight'] = freight['kms']*freight['freightxkms']
freight.head()

,source,destination,kms,freightxkms,freight
0,Aguascalientes,Aguascalientes,0.000000,0.000313,0.000000
1,Aguascalientes,Aguascalientes_aggregate(10),9.246637,0.000313,0.002890
2,Aguascalientes,Baja California_aggregate(5),1504.807282,0.000313,0.470340
3,Aguascalientes,Tijuana,1659.159609,0.000313,0.518585
4,Aguascalientes,Baja California Sur_aggregate(5),914.986938,0.000313,0.285987

In [15]:
specific_states_rates = {
    'Baja California': 1.2, # Peninsula
    'Baja California Sur': 1.5, # Peninsula
    'Yucatán': 1.3, # Peninsula
    'Oaxaca': 1.2, # Mountain range
    'San Luis Potosí': 0.85 # Logistics hub
}

specific_state_connection_rates = {
    ('Baja California', 'Baja California Sur'): 1.3, # Mountain range
    ('Oaxaca', 'Baja California Sur'): 0.2, # Vessel
    ('Tamaulipas', 'Yucatán'): 0.2, # Vessel
    ('Veracruz de Ignacio de la Llave', 'Yucatán'): 0.2, # Vessel
}

freight = sess().fix_freight(w, freight, overall_mxnxkms_L, specific_state_connection_rates, specific_states_rates)
freight.head()

Modifying rates for specifig state connections
Modifying rates for states

,source,destination,kms,freightxkms,freight
0,Aguascalientes,Aguascalientes,0.000000,0.000313,0.000000
1,Aguascalientes,Aguascalientes_aggregate(10),9.246637,0.000313,0.002890
2,Aguascalientes,Baja California_aggregate(5),1504.807282,0.000375,0.564409
3,Aguascalientes,Tijuana,1659.159609,0.000375,0.622302
4,Aguascalientes,Baja California Sur_aggregate(5),914.986938,0.000469,0.428981

In [16]:
freight.loc[(freight.freightxkms==overall_mxnxkms_L*0.2)]

,source,destination,kms,freightxkms,freight
4804,Oaxaca de Juárez,Baja California Sur_aggregate(5),1540.029146,0.000063,0.096270
4900,Oaxaca_aggregate(159),Baja California Sur_aggregate(5),1578.129831,0.000063,0.098652
7186,Matamoros,Mérida,877.591435,0.000063,0.054860
7187,Matamoros,Yucatán_aggregate(86),929.426292,0.000063,0.058100
7282,Nuevo Laredo,Mérida,1115.524277,0.000063,0.069733
7283,Nuevo Laredo,Yucatán_aggregate(86),1167.200046,0.000063,0.072964
7378,Reynosa,Mérida,971.033739,0.000063,0.060701
7379,Reynosa,Yucatán_aggregate(86),1022.852461,0.000063,0.063940
7474,Tamaulipas_aggregate(26),Mérida,944.883590,0.000063,0.059066
7475,Tamaulipas_aggregate(26),Yucatán_aggregate(86),996.840719,0.000063,0.062314
7570,Victoria,Mérida,1059.336662,0.000063,0.066221
7571,Victoria,Yucatán_aggregate(86),1111.273886,0.000063,0.069468
7762,Veracruz,Mérida,731.893648,0.000063,0.045752
7763,Veracruz,Yucatán_aggregate(86),783.880185,0.000063,0.049002
7858,Veracruz de Ignacio de la Llave_aggregate(167),Mérida,753.582053,0.000063,0.047108
7859,Veracruz de Ignacio de la Llave_aggregate(167),Yucatán_aggregate(86),805.569699,0.000063,0.050358
8626,Madero Refinery,Mérida,12503.030943,0.000063,0.781586
8627,Madero Refinery,Yucatán_aggregate(86),12527.669996,0.000063,0.783126
8914,Minatitlan Refinery,Mérida,12024.592560,0.000063,0.751678
8915,Minatitlan Refinery,Yucatán_aggregate(86),12046.606209,0.000063,0.753054
8932,Salina Cruz Refinery,Baja California Sur_aggregate(5),10627.528371,0.000063,0.664345
9106,Cangrejera Refinery,Mérida,12036.439494,0.000063,0.752419
9107,Cangrejera Refinery,Yucatán_aggregate(86),12058.309246,0.000063,0.753786

# Create production variables

In [17]:
production = sess().get_refinery_data()
production

,state,loc,lat,lon,daily_capacity
0,Nuevo León,Cadereyta Refinery,25.594537,-99.945843,16544839.46
1,Tamaulipas,Madero Refinery,22.269130,-97.810817,14331101.70
2,Ciudad de México,Tula Refinery,20.047802,-99.272312,15242115.59
3,Guanajuato,Salamanca Refinery,20.583399,-101.185100,15123218.22
4,Veracruz de Ignacio de la Llave,Minatitlan Refinery,17.984720,-94.533883,13445967.28
5,Oaxaca,Salina Cruz Refinery,16.218273,-95.185282,20078625.37
6,Veracruz de Ignacio de la Llave,Cangrejera Refinery,18.092251,-94.360367,0.00
7,Tabasco,Dos Bocas Refinery,18.422020,-93.192958,27027841.46

# Fixed costs

In [18]:
fixed = 2500000
fixed_costs_dict = {'fixed': {
    'Cadereyta Refinery': 5.0,
    'Madero Refinery': 5.0,
    'Tula Refinery': 5.0,
    'Salamanca Refinery': 5.0,
    'Minatitlan Refinery': 5.0,
    'Salina Cruz Refinery': 5.0,
    'Cangrejera Refinery': 5.0,
    'Dos Bocas Refinery': 5.0
}}

production = pd.merge(
    left=production,
    right=pd.DataFrame(fixed_costs_dict),
    left_on = 'loc',
    right_index=True
).assign(fixed=lambda r: r.daily_capacity*r.fixed*30+fixed)
production

,state,loc,lat,lon,daily_capacity,fixed
0,Nuevo León,Cadereyta Refinery,25.594537,-99.945843,16544839.46,2.484226e+09
1,Tamaulipas,Madero Refinery,22.269130,-97.810817,14331101.70,2.152165e+09
2,Ciudad de México,Tula Refinery,20.047802,-99.272312,15242115.59,2.288817e+09
3,Guanajuato,Salamanca Refinery,20.583399,-101.185100,15123218.22,2.270983e+09
4,Veracruz de Ignacio de la Llave,Minatitlan Refinery,17.984720,-94.533883,13445967.28,2.019395e+09
5,Oaxaca,Salina Cruz Refinery,16.218273,-95.185282,20078625.37,3.014294e+09
6,Veracruz de Ignacio de la Llave,Cangrejera Refinery,18.092251,-94.360367,0.00,2.500000e+06
7,Tabasco,Dos Bocas Refinery,18.422020,-93.192958,27027841.46,4.056676e+09

# Variable costs

In [19]:
variable = 4
variable_costs_dict = {'variable': {
    'Cadereyta Refinery': 1.0/1e7,
    'Madero Refinery': 1.0/1e7,
    'Tula Refinery': 1.0/1e7,
    'Salamanca Refinery': 1.0/1e7,
    'Minatitlan Refinery': 1.0/1e7,
    'Salina Cruz Refinery': 1.0/1e7,
    'Cangrejera Refinery': 1.0/1e7,
    'Dos Bocas Refinery': 1.0/1e7
}}

production = pd.merge(
    left=production,
    right=pd.DataFrame(variable_costs_dict),
    left_on = 'loc',
    right_index=True
).assign(variable=lambda r: r.daily_capacity*r.variable+variable)
production

,state,loc,lat,lon,daily_capacity,fixed,variable
0,Nuevo León,Cadereyta Refinery,25.594537,-99.945843,16544839.46,2.484226e+09,5.654484
1,Tamaulipas,Madero Refinery,22.269130,-97.810817,14331101.70,2.152165e+09,5.433110
2,Ciudad de México,Tula Refinery,20.047802,-99.272312,15242115.59,2.288817e+09,5.524212
3,Guanajuato,Salamanca Refinery,20.583399,-101.185100,15123218.22,2.270983e+09,5.512322
4,Veracruz de Ignacio de la Llave,Minatitlan Refinery,17.984720,-94.533883,13445967.28,2.019395e+09,5.344597
5,Oaxaca,Salina Cruz Refinery,16.218273,-95.185282,20078625.37,3.014294e+09,6.007863
6,Veracruz de Ignacio de la Llave,Cangrejera Refinery,18.092251,-94.360367,0.00,2.500000e+06,4.000000
7,Tabasco,Dos Bocas Refinery,18.422020,-93.192958,27027841.46,4.056676e+09,6.702784

# Storage capacity

In [20]:
storage = 300000
storage_dict = {'storage': {
    'Cadereyta Refinery': 15, # capacity in terms of production days
    'Madero Refinery': 15,
    'Tula Refinery': 15,
    'Salamanca Refinery': 15,
    'Minatitlan Refinery': 15,
    'Salina Cruz Refinery': 15,
    'Cangrejera Refinery': 15,
    'Dos Bocas Refinery': 15
}}

production = pd.merge(
    left=production,
    right=pd.DataFrame(storage_dict),
    left_on = 'loc',
    right_index=True
).assign(storage=lambda r: r.daily_capacity*r.storage+storage)
production

,state,loc,lat,lon,daily_capacity,fixed,variable,storage
0,Nuevo León,Cadereyta Refinery,25.594537,-99.945843,16544839.46,2.484226e+09,5.654484,2.484726e+08
1,Tamaulipas,Madero Refinery,22.269130,-97.810817,14331101.70,2.152165e+09,5.433110,2.152665e+08
2,Ciudad de México,Tula Refinery,20.047802,-99.272312,15242115.59,2.288817e+09,5.524212,2.289317e+08
3,Guanajuato,Salamanca Refinery,20.583399,-101.185100,15123218.22,2.270983e+09,5.512322,2.271483e+08
4,Veracruz de Ignacio de la Llave,Minatitlan Refinery,17.984720,-94.533883,13445967.28,2.019395e+09,5.344597,2.019895e+08
5,Oaxaca,Salina Cruz Refinery,16.218273,-95.185282,20078625.37,3.014294e+09,6.007863,3.014794e+08
6,Veracruz de Ignacio de la Llave,Cangrejera Refinery,18.092251,-94.360367,0.00,2.500000e+06,4.000000,3.000000e+05
7,Tabasco,Dos Bocas Refinery,18.422020,-93.192958,27027841.46,4.056676e+09,6.702784,4.057176e+08

# Safety inventories when turned on

In [21]:
safety_inventory = 300000
safety_inventory_dict = {'safety_inventory': {
    'Cadereyta Refinery': 1,
    'Madero Refinery': 1,
    'Tula Refinery': 1,
    'Salamanca Refinery': 1,
    'Minatitlan Refinery': 1,
    'Salina Cruz Refinery': 1,
    'Cangrejera Refinery': 1,
    'Dos Bocas Refinery': 1
}}

production = pd.merge(
    left=production,
    right=pd.DataFrame(safety_inventory_dict),
    left_on = 'loc',
    right_index=True
).assign(safety_inventory=lambda r: r.daily_capacity*r.safety_inventory+safety_inventory)
production

,state,loc,lat,lon,daily_capacity,fixed,variable,storage,safety_inventory
0,Nuevo León,Cadereyta Refinery,25.594537,-99.945843,16544839.46,2.484226e+09,5.654484,2.484726e+08,16844839.46
1,Tamaulipas,Madero Refinery,22.269130,-97.810817,14331101.70,2.152165e+09,5.433110,2.152665e+08,14631101.70
2,Ciudad de México,Tula Refinery,20.047802,-99.272312,15242115.59,2.288817e+09,5.524212,2.289317e+08,15542115.59
3,Guanajuato,Salamanca Refinery,20.583399,-101.185100,15123218.22,2.270983e+09,5.512322,2.271483e+08,15423218.22
4,Veracruz de Ignacio de la Llave,Minatitlan Refinery,17.984720,-94.533883,13445967.28,2.019395e+09,5.344597,2.019895e+08,13745967.28
5,Oaxaca,Salina Cruz Refinery,16.218273,-95.185282,20078625.37,3.014294e+09,6.007863,3.014794e+08,20378625.37
6,Veracruz de Ignacio de la Llave,Cangrejera Refinery,18.092251,-94.360367,0.00,2.500000e+06,4.000000,3.000000e+05,300000.00
7,Tabasco,Dos Bocas Refinery,18.422020,-93.192958,27027841.46,4.056676e+09,6.702784,4.057176e+08,27327841.46

# Production time series

In [22]:
t = 0
production['T'] = t
production['days'] = period_stats.loc[period_stats['T']==t].days.values[0]
for t in range(1,opt_periods):
    days = period_stats.loc[period_stats['T']==t].days.values[0]
    production = pd.concat(
        [production, production.assign(T=t, days=days)], axis = 0
    )
production.reset_index(drop=True, inplace=True)
production['capacity'] = production['daily_capacity']*production['days']
production

,state,loc,lat,lon,daily_capacity,fixed,variable,storage,safety_inventory,T,days,capacity
0,Nuevo León,Cadereyta Refinery,25.594537,-99.945843,16544839.46,2.484226e+09,5.654484,2.484726e+08,16844839.46,0,31,5.128900e+08
1,Tamaulipas,Madero Refinery,22.269130,-97.810817,14331101.70,2.152165e+09,5.433110,2.152665e+08,14631101.70,0,31,4.442642e+08
2,Ciudad de México,Tula Refinery,20.047802,-99.272312,15242115.59,2.288817e+09,5.524212,2.289317e+08,15542115.59,0,31,4.725056e+08
3,Guanajuato,Salamanca Refinery,20.583399,-101.185100,15123218.22,2.270983e+09,5.512322,2.271483e+08,15423218.22,0,31,4.688198e+08
4,Veracruz de Ignacio de la Llave,Minatitlan Refinery,17.984720,-94.533883,13445967.28,2.019395e+09,5.344597,2.019895e+08,13745967.28,0,31,4.168250e+08
...,...,...,...,...,...,...,...,...,...,...,...,...
1019,Guanajuato,Salamanca Refinery,20.583399,-101.185100,15123218.22,2.270983e+09,5.512322,2.271483e+08,15423218.22,7,31,4.688198e+08
1020,Veracruz de Ignacio de la Llave,Minatitlan Refinery,17.984720,-94.533883,13445967.28,2.019395e+09,5.344597,2.019895e+08,13745967.28,7,31,4.168250e+08
1021,Oaxaca,Salina Cruz Refinery,16.218273,-95.185282,20078625.37,3.014294e+09,6.007863,3.014794e+08,20378625.37,7,31,6.224374e+08
1022,Veracruz de Ignacio de la Llave,Cangrejera Refinery,18.092251,-94.360367,0.00,2.500000e+06,4.000000,3.000000e+05,300000.00,7,31,0.000000e+00
1023,Tabasco,Dos Bocas Refinery,18.422020,-93.192958,27027841.46,4.056676e+09,6.702784,4.057176e+08,27327841.46,7,31,8.378631e+08

# CAPEX Projects

In [23]:
capex_projects = {'capex': {
    'Cadereyta Refinery': 0,
    'Madero Refinery': 0,
    'Tula Refinery': 0,
    'Salamanca Refinery': 0,
    'Minatitlan Refinery': 0,
    'Salina Cruz Refinery': 0,
    'Cangrejera Refinery': 0,
    'Dos Bocas Refinery': 22000e6
    }
}

capex_projects = pd.DataFrame(capex_projects)

capex_projects['type'] = 'INITIAL'
capex_projects

                             capex     type
Cadereyta Refinery    0.000000e+00  INITIAL
Cangrejera Refinery   0.000000e+00  INITIAL
Dos Bocas Refinery    2.200000e+10  INITIAL
Madero Refinery       0.000000e+00  INITIAL
Minatitlan Refinery   0.000000e+00  INITIAL
Salamanca Refinery    0.000000e+00  INITIAL
Salina Cruz Refinery  0.000000e+00  INITIAL
Tula Refinery         0.000000e+00  INITIAL

In [24]:
strategic_projects = {'capex': {
    'Cadereyta Refinery': 300e6,
    'Madero Refinery': 300e6,
    'Tula Refinery': 300e6,
    'Salamanca Refinery': 300e6,
    'Minatitlan Refinery': 300e6,
    'Salina Cruz Refinery': 300e6,
    'Cangrejera Refinery': 70000e6,
    'Dos Bocas Refinery': 0
    },
    'increment': {
    'Cadereyta Refinery': 1.2,
    'Madero Refinery': 1.2,
    'Tula Refinery': 1.3,
    'Salamanca Refinery': 1.4,
    'Minatitlan Refinery': 1.2,
    'Salina Cruz Refinery': 1.2,
    'Cangrejera Refinery': 1.2,
    'Dos Bocas Refinery': 0
    }
}

strategic_projects = pd.DataFrame(strategic_projects)

strategic_projects['type'] = 'STRATEGIC'
strategic_projects

                             capex  increment       type
Cadereyta Refinery    3.000000e+08        1.2  STRATEGIC
Madero Refinery       3.000000e+08        1.2  STRATEGIC
Tula Refinery         3.000000e+08        1.3  STRATEGIC
Salamanca Refinery    3.000000e+08        1.4  STRATEGIC
Minatitlan Refinery   3.000000e+08        1.2  STRATEGIC
Salina Cruz Refinery  3.000000e+08        1.2  STRATEGIC
Cangrejera Refinery   7.000000e+10        1.2  STRATEGIC
Dos Bocas Refinery    0.000000e+00        0.0  STRATEGIC

In [25]:
projects = pd.concat(
    [capex_projects, strategic_projects],
    axis=0
)
projects.index.names = ['loc']

projects = projects.reset_index()

# Quick sanity checks before optimizing

In [26]:
print(f'Capacity/Demand: {100*production.capacity.sum()/demand.litres.sum():,.2f}%')

Capacity/Demand: 28.54%

In [27]:
print('Sold out costs description:\n', (production.fixed/production.capacity+production.variable).replace(np.inf, np.nan).describe())

Sold out costs description:
 count    896.000000
mean      10.612776
std        0.445271
min       10.189304
25%       10.350794
50%       10.403569
75%       10.850589
max       12.063230
dtype: float64

In [28]:
print('Price description:\n', price.price.describe())

Price description:
 count    1056.000000
mean       18.257608
std         2.475572
min         8.118163
25%        16.796996
50%        18.165370
75%        19.534997
max        32.265917
Name: price, dtype: float64

In [69]:
REFINERIES=list(production['loc'].drop_duplicates().values)
LOCATIONS=list(demand['loc'].drop_duplicates().values)

WACC = 0.1
depreciation_years=10
minimum_production_period=3

opt_timelimit=60*5
mip_tolerance=1e-4

save_path="\\content\\scenarios\\"
opt_version='baseline'
step=0

fuel_opt = sess().get_fuel_opt_model(opt_periods, REFINERIES, LOCATIONS, demand, price, freight, production, projects, WACC, depreciation_years, minimum_production_period)

In [70]:
sess().optimize_MIP_model(fuel_opt, opt_timelimit, mip_tolerance, save_path, opt_version, step)

Solver log file: '\content\scenarios\baseline\LOGS\baseline_0.log'
Solver solution file: '/tmp/tmpczwhbucn.glpk.raw'
Solver problem files: ('/tmp/tmpvew88b8e.pyomo.lp',)
GLPSOL: GLPK LP/MIP Solver, v4.65
Parameter(s) specified in the command line:
 --tmlim 300 --mipgap 0.0001 --write /tmp/tmpczwhbucn.glpk.raw --wglp /tmp/tmpq2tlw83z.glpk.glp
 --cpxlp /tmp/tmpvew88b8e.pyomo.lp
Reading problem data from '/tmp/tmpvew88b8e.pyomo.lp'...
/tmp/tmpvew88b8e.pyomo.lp:112131: warning: lower bound of variable 'x5584' redefined
/tmp/tmpvew88b8e.pyomo.lp:112131: warning: upper bound of variable 'x5584' redefined
14497 rows, 11825 columns, 50440 non-zeros
1384 integer variables, all of which are binary
113515 lines were read
Writing problem data to '/tmp/tmpq2tlw83z.glpk.glp'...
103558 lines were written
GLPK Integer Optimizer, v4.65
14497 rows, 11825 columns, 50440 non-zeros
1384 integer variables, all of which are binary
Preprocessing...
6765 rows, 9153 columns, 35285 non-zeros
1118 integer variables, all of which are binary
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  8.379e+08  ratio =  8.379e+08
GM: min|aij| =  3.236e-01  max|aij| =  3.090e+00  ratio =  9.547e+00
EQ: min|aij| =  1.148e-01  max|aij| =  1.000e+00  ratio =  8.713e+00
2N: min|aij| =  6.250e-02  max|aij| =  1.629e+00  ratio =  2.606e+01
Constructing initial basis...
Size of triangular part is 6765
Solving LP relaxation...
GLPK Simplex Optimizer, v4.65
6765 rows, 9153 columns, 35285 non-zeros
*     0: obj =  -0.000000000e+00 inf =   0.000e+00 (2273)
Perturbing LP to avoid stalling [199]...
Removing LP perturbation [421]...
*   421: obj =   5.599477186e+10 inf =   0.000e+00 (0) 3
OPTIMAL LP SOLUTION FOUND
Integer optimization begins...
Long-step dual simplex will be used
+   421: mip =     not found yet <=              +inf        (1; 0)
+   421: >>>>>   5.599477186e+10 <=   5.599477186e+10   0.0% (1; 0)
+   421: mip =   5.599477186e+10 <=     tree is empty   0.0% (0; 1)
INTEGER OPTIMAL SOLUTION FOUND
Time used:   0.1 secs
Memory used: 17.1 Mb (17897919 bytes)
Writing MIP solution to '/tmp/tmpczwhbucn.glpk.raw'...
26331 lines were written

({'Problem': [{'Name': 'unknown', 'Lower bound': 55994771861.2024, 'Upper bound': 55994771861.2024, 'Number of objectives': 1, 'Number of constraints': 14497, 'Number of variables': 11825, 'Number of nonzeros': 50440, 'Sense': 'maximize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': '1', 'Number of created subproblems': '1'}}, 'Error rc': 0, 'Time': 0.26506567001342773}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]},
 0.0)

In [71]:
import pyomo.environ as pme

In [72]:
market_stats = pd.concat(
    [
        pd.DataFrame({'sales': {(t, mkt, plant): pme.value(fuel_opt.MARKETS[t, mkt].L[plant]) for t in fuel_opt.T for mkt in fuel_opt.LOCATIONS for plant in fuel_opt.REFINERIES}}),
    ], axis=1
)

In [73]:
prod_stats = pd.concat(
    [
        pd.DataFrame({'capcity': {(t, plant): pme.value(fuel_opt.PLANTS[t, plant].CAPACITY) for t in fuel_opt.T for plant in fuel_opt.REFINERIES}}),
        pd.DataFrame({'production': {(t, plant): pme.value(fuel_opt.PLANTS[t, plant].L) for t in fuel_opt.T for plant in fuel_opt.REFINERIES}}),
        pd.DataFrame({'capex': {(t, plant): pme.value(fuel_opt.PLANTS[t, plant].CAPEX_COSTS_Expression) for t in fuel_opt.T for plant in fuel_opt.REFINERIES}}),
        pd.DataFrame({'state': {(t, plant): pme.value(fuel_opt.PLANTS[t, plant].STATE) for t in fuel_opt.T for plant in fuel_opt.REFINERIES}}),
        pd.DataFrame({'available': {(t, plant): pme.value(fuel_opt.PLANTS[t, plant].AVAILABLE) for t in fuel_opt.T for plant in fuel_opt.REFINERIES}}),
        pd.DataFrame({'expansion': {(t, plant): pme.value(fuel_opt.PLANTS[t, plant].EXPANSION) for t in fuel_opt.T for plant in fuel_opt.REFINERIES}})
    ], axis=1
)

In [74]:
prod_stats

                             capcity    production  capex  state  available  \
0 Cadereyta Refinery    5.128900e+08  0.000000e+00    0.0    0.0        1.0
  Cangrejera Refinery   0.000000e+00  0.000000e+00    0.0    0.0        0.0
  Dos Bocas Refinery    8.378631e+08  0.000000e+00    0.0    0.0        0.0
  Madero Refinery       4.442642e+08  0.000000e+00    0.0    0.0        1.0
  Minatitlan Refinery   4.168250e+08  0.000000e+00    0.0    0.0        1.0
...                              ...           ...    ...    ...        ...
7 Madero Refinery       4.442642e+08  5.331170e+08    0.0    1.0        1.0
  Minatitlan Refinery   4.168250e+08  5.001900e+08    0.0    1.0        1.0
  Salamanca Refinery    4.688198e+08  6.563477e+08    0.0    1.0        1.0
  Salina Cruz Refinery  6.224374e+08  7.469249e+08    0.0    1.0        1.0
  Tula Refinery         4.725056e+08  6.142573e+08    0.0    1.0        1.0

                        expansion
0 Cadereyta Refinery          0.0
  Cangrejera Refinery         0.0
  Dos Bocas Refinery          0.0
  Madero Refinery             0.0
  Minatitlan Refinery         0.0
...                           ...
7 Madero Refinery             1.0
  Minatitlan Refinery         1.0
  Salamanca Refinery          1.0
  Salina Cruz Refinery        1.0
  Tula Refinery               1.0

[64 rows x 6 columns]

In [79]:
prod_stats.loc[(slice(None), 'Dos Bocas Refinery'),:]

,,capcity,production,capex,state,available,expansion
0,Dos Bocas Refinery,8.378631e+08,0.0,0.0,0.0,0.0,0.0
1,Dos Bocas Refinery,7.567796e+08,0.0,0.0,0.0,0.0,0.0
2,Dos Bocas Refinery,8.378631e+08,0.0,0.0,0.0,0.0,0.0
3,Dos Bocas Refinery,8.108352e+08,0.0,0.0,0.0,0.0,0.0
4,Dos Bocas Refinery,8.378631e+08,0.0,0.0,0.0,0.0,0.0
5,Dos Bocas Refinery,8.108352e+08,0.0,0.0,0.0,0.0,0.0
6,Dos Bocas Refinery,8.378631e+08,0.0,0.0,0.0,0.0,0.0
7,Dos Bocas Refinery,8.378631e+08,0.0,0.0,0.0,0.0,0.0

In [76]:
prod_stats.production.sum()

21761292927.848

In [77]:
prod_stats.capex.sum()

1800000000.0

In [78]:
prod_stats.expansion.sum()

42.0

# Now that you know how to optimize a sinlge scenario, lets wrap thoe functions into a loop to iteratevly solve for different scenario to make an assesment